/* eslint-disable no-await-in-loop */
/**
 * PTA fork — the AI CLASS REPORT of a HOMEWORK or TEST ("activity"),
 * generated by a BACKGROUND JOB the page polls.
 *
 * What the model reads (buildActivityCorpus):
 *   - every task of the activity with its kind (programming / objective /
 *     subjective), knowledge points (catalog paths), weight, difficulty and
 *     STATEMENT — for objective tasks the question, its options and the
 *     ANSWER KEY (from config.yaml);
 *   - every student's every judged submission on every task, in order,
 *     with the code of the accepted attempt (or the last failing one) for
 *     programming tasks and the ANSWERS GIVEN, question by question, for
 *     objective tasks (so a wrong choice can be read as a misconception);
 *   - the scoreboard score of every student, hand-ins of subjective tasks;
 *   - deterministic STATISTICS the report may quote: participation, score
 *     distribution, per task (verdicts, first failures, attempts, time to
 *     accept, objective accuracy per question with the distribution of
 *     chosen options), per knowledge point, submission timeline against
 *     the deadline, late work, languages.
 *
 * How (runActivityReportJob): collect → MAP (students packed into batches
 * by size, each batch read by the model into structured findings; a
 * per-student cache keyed by the transcript's hash spares unchanged
 * students on a re-run; a failing batch is bisected and retried tighter)
 * → REDUCE (one report from the statistics + merged findings) → names
 * substituted for the S-tokens → stored. Progress lives on the report
 * document (setClassReportJob) so a refresh or a second tab re-attaches.
 *
 * SCALE. Built for classes of 200+ students: the corpus never loads code
 * in bulk (only the one excerpt per programming cell, in chunks); batches
 * are packed by characters with the task block's size taken off the
 * budget, and the whole class drops to a tighter transcript level when
 * the call count would exceed the ceiling (ai_tutor.report_max_calls);
 * transient provider errors (429 / 5xx / timeouts) are retried with
 * backoff under a process-wide cooldown before a batch is ever split; a
 * malformed reply is asked once more; progress is heart-beaten after every
 * batch, and a job counts as dead only when the heartbeat goes silent —
 * never merely because it started long ago.
 *
 * handler/self_learning.ts AiClassReportHandler starts the job and serves
 * the report; lib/ai_tutor.ts holds the two prompts and the retry helper.
 */
import { createHash } from 'crypto';
import { load as yamlLoad } from 'js-yaml';
import { STATUS, STATUS_SHORT_TEXTS, STATUS_TEXTS } from '@hydrooj/common';
import { Logger } from '../logger';
import * as aiTutor from './ai_tutor';
import { objectiveSubKindOf } from './objective_markdown';
import { readRawProblemConfig } from './problem_config';
import * as contest from '../model/contest';
import KnowledgeModel from '../model/knowledge';
import problem from '../model/problem';
import record from '../model/record';
import {
    getClassReportMapCache, listSubjective, setClassReport, setClassReportJob, setClassReportMapCache,
} from '../model/selflearning';
import * as setting from '../model/setting';
import system from '../model/system';
import user from '../model/user';

const logger = new Logger('activity-report');

/* ------------------------------ limits ------------------------------ */

const MAX_STUDENTS = 600;
const MAX_RECORDS = 60000;
const MAX_TASKS = 80;
const CODE_AC_CAP = 1200;
const CODE_FAIL_CAP = 900;
const STATEMENT_CAP = 700;
const QUESTION_CAP = 240;
const OPTION_CAP = 90;
const BATCH_CHARS = () => Math.max(12000, +system.get('ai_tutor.report_batch_chars') || 48000);
const REDUCE_CHARS = () => Math.max(30000, +system.get('ai_tutor.report_reduce_chars') || 110000);
const MAP_CONCURRENCY = () => Math.min(8, Math.max(1, +system.get('ai_tutor.report_concurrency') || 3));
const MAX_CALLS = () => Math.max(8, +system.get('ai_tutor.report_max_calls') || 40);
const NONFINAL_STATUS = [0, 20, 21, 22]; // waiting / judging / compiling / fetched
/**
 * 💓 A running job is dead when its HEARTBEAT (the last progress write,
 * model classReportJobStale) is older than this — not when it merely
 * started long ago: a 200-student class means dozens of model calls and
 * well over half an hour, with a heartbeat after every batch (each call
 * is capped at five minutes, the reduce at seven).
 */
export const ACTIVITY_JOB_STALE_MS = 15 * 60 * 1000;

/** Transcript compaction levels: code caps and which objective answers are listed. */
const LEVELS: { code: number, wrongOnly: boolean, collapse: boolean }[] = [
    { code: CODE_AC_CAP, wrongOnly: false, collapse: false },
    { code: 600, wrongOnly: true, collapse: true },
    { code: 300, wrongOnly: true, collapse: true },
];

/* ------------------------------ helpers ------------------------------ */

const median = (xs: number[]) => {
    if (!xs.length) return 0;
    const a = [...xs].sort((x, y) => x - y);
    const m = Math.floor(a.length / 2);
    return a.length % 2 ? a[m] : Math.round(((a[m - 1] + a[m]) / 2) * 10) / 10;
};
const mean1 = (xs: number[]) => (xs.length ? Math.round((xs.reduce((a, b) => a + b, 0) / xs.length) * 10) / 10 : null);
const pct = (a: number, b: number) => (b ? Math.round((a / b) * 100) : 0);
const verdictOf = (status: number) => STATUS_SHORT_TEXTS[status] || STATUS_TEXTS[status] || String(status);
const cut = (s: any, n: number) => {
    const t = String(s ?? '');
    return t.length > n ? `${t.slice(0, n)}…` : t;
};
const oneLine = (s: any) => String(s ?? '').replace(/\s+/g, ' ').trim();
/** config.yaml (a raw string in list projections) → object, or null when unparsable. */
function parseConfig(cfg: any): any {
    if (typeof cfg !== 'string') return cfg && typeof cfg === 'object' ? cfg : null;
    try {
        return yamlLoad(cfg);
    } catch (e) {
        return null;
    }
}

/** Markdown → readable plain text for the model (headings, emphasis, links, images stripped). */
function plainText(md: string): string {
    return String(md || '')
        .replace(/```[\s\S]*?```/g, (m) => m.replace(/```\w*\n?/g, '').trim())
        .replace(/!\[[^\]]*\]\([^)]*\)/g, ' ')
        .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
        .replace(/^#{1,6}\s+/gm, '')
        .replace(/[*_~`>]+/g, '')
        .replace(/\r/g, '')
        .replace(/[ \t]+/g, ' ')
        .replace(/\n{3,}/g, '\n\n')
        .trim();
}

/** The task kind by the site's P/O/S convention, falling back to the config type. */
function kindOf(pdoc: any): 'programming' | 'objective' | 'subjective' {
    const pid = String(pdoc?.pid || '');
    if (/^o/i.test(pid)) return 'objective';
    if (/^s/i.test(pid)) return 'subjective';
    const cfg = parseConfig(pdoc?.config);
    if (cfg && typeof cfg === 'object' && cfg.type === 'objective') return 'objective';
    return 'programming';
}

/* ------------------------- objective questions ------------------------- */

export interface ObjectiveQuestion {
    key: string;
    kind: 'select' | 'multiselect' | 'input';
    prompt: string;
    options: { letter: string, text: string }[];
    answer: string[];
    score: number;
}

const MARKER_RE = /\{\{\s*(input|select|multiselect|textarea|dropdown)\((\d+(?:-\d+)?)\)(?:\[[^\]]*\])?\s*\}\}/g;

/**
 * The questions of an objective task: each `{{ select(n) }}`-style marker
 * with the text before it (its prompt), the option lines listed under it
 * (lettered A, B, C… as the builder and the judge do) and the answer key
 * of config.yaml (`answers: { "n": [answer, score] }` or `{ "n": { answer:
 * score } }`).
 */
export function objectiveQuestionsOf(statement: string, config: any): ObjectiveQuestion[] {
    const md = String(statement || '').replace(/\r/g, '');
    const answers = (config && typeof config === 'object' && config.answers && typeof config.answers === 'object') ? config.answers : {};
    const out: ObjectiveQuestion[] = [];
    const markers: { key: string, tag: string, index: number, end: number }[] = [];
    for (const m of md.matchAll(MARKER_RE)) markers.push({ key: m[2], tag: m[1], index: m.index!, end: m.index! + m[0].length });
    for (let i = 0; i < markers.length; i++) {
        const mk = markers[i];
        const before = md.slice(i ? markers[i - 1].end : 0, mk.index);
        // Options: the list items that directly follow the marker.
        const after = md.slice(mk.end, i + 1 < markers.length ? markers[i + 1].index : md.length);
        const options: { letter: string, text: string }[] = [];
        let promptTail = '';
        const lines = after.split('\n');
        let started = false;
        for (const line of lines) {
            const om = /^[ \t]*[-*+][ \t]+(\S.*)?$/.exec(line);
            if (om) {
                started = true;
                options.push({ letter: String.fromCharCode(65 + options.length), text: cut(oneLine((om[1] || '').replace(/^\\/, '')), OPTION_CAP) });
            } else if (started && line.trim()) break;
        }
        // The prompt: the last paragraph before the marker (plus what
        // precedes the option list when the marker sits at the very top).
        const promptSrc = plainText(before).split(/\n\s*\n/).filter((x) => x.trim());
        const prompt = promptSrc.length ? promptSrc[promptSrc.length - 1] : promptTail;
        const raw = answers[mk.key];
        let answer: string[] = [];
        let score = 0;
        if (Array.isArray(raw)) {
            answer = Array.isArray(raw[0]) ? raw[0].map(String) : [String(raw[0])];
            score = +raw[1] || 0;
        } else if (raw && typeof raw === 'object') {
            // `{ answer: score }` — the best-scoring answer(s) are "the" answer.
            const entries = Object.entries(raw).map(([k, v]) => [k, +v || 0] as [string, number]);
            const best = Math.max(0, ...entries.map((e) => e[1]));
            answer = entries.filter((e) => e[1] === best && best > 0).map((e) => e[0]);
            score = best;
        }
        out.push({
            key: mk.key,
            kind: mk.tag === 'multiselect' ? 'multiselect' : (mk.tag === 'select' || mk.tag === 'dropdown') ? 'select' : 'input',
            prompt: cut(oneLine(prompt), QUESTION_CAP),
            options,
            answer,
            score,
        });
        promptTail = '';
    }
    return out;
}

/** A student's YAML answer sheet → { key: answer(s) } (strings). */
export function parseAnswerSheet(code: string): Record<string, string[]> {
    let doc: any;
    try {
        doc = yamlLoad(String(code || '').replace(/\r/g, ''));
    } catch (e) {
        return {};
    }
    if (!doc || typeof doc !== 'object') return {};
    const out: Record<string, string[]> = {};
    for (const [k, v] of Object.entries(doc)) {
        if (v === null || v === undefined) continue;
        out[String(k)] = (Array.isArray(v) ? v : [v]).map((x) => oneLine(x)).filter((x) => x !== '');
    }
    return out;
}

export const sameSet = (a: string[], b: string[]) => a.length === b.length && a.every((x) => b.includes(x));

/* ------------------------------ corpus ------------------------------ */

export interface ActivityTask {
    pid: number;
    label: string;
    title: string;
    kind: 'programming' | 'objective' | 'subjective';
    sub?: 'tf' | 'choice' | 'blank' | null;
    points: string[];
    pointPaths: string[];
    difficulty: number;
    weight: number;
    statement: string;
    questions: ObjectiveQuestion[];
}

interface Cell {
    attempts: { status: number, score: number, at: Date, rid: any, lang: string }[];
    firstAt: Date | null;
    acAt: Date | null;
    acRid: any;
    lastFailRid: any;
    lastFailStatus: number;
    best: { score: number, rid: any, at: Date } | null;
}

export async function buildActivityCorpus(domainId: string, tdoc: any, kind: 'homework' | 'contest', light: boolean) {
    const pidsAll: number[] = (tdoc.pids || []).filter((x: any) => typeof x === 'number');
    const pids = pidsAll.slice(0, MAX_TASKS);
    // `data` is projected so the RAW config.yaml can be read back for
    // objective tasks: the normalized config getList returns keeps `type`
    // but drops the `answers` key (and the matching flags).
    const pdict = await problem.getList(domainId, pids, true, false, ['docId', 'pid', 'title', 'difficulty', 'tag', 'config', 'content', 'data'] as any, true);
    const tasks: ActivityTask[] = [];
    for (const pid of pids) {
        const pd: any = pdict[pid];
        if (!pd) continue;
        const k = kindOf(pd);
        const statement = plainText(aiTutor.resolveStatement(pd, 'en'));
        const cfg = k === 'objective' ? await readRawProblemConfig({ domainId, docId: pid, data: pd.data }) : parseConfig(pd.config);
        const points = (pd.tag || []).map((t: any) => String(t)).filter((t: string) => t);
        tasks.push({
            pid,
            label: String(pd.pid || `P${pid}`),
            title: pd.title || '',
            kind: k,
            sub: k === 'objective' ? objectiveSubKindOf(pd.content) : null,
            points,
            pointPaths: await KnowledgeModel.describeTags(domainId, points).catch(() => points),
            difficulty: pd.difficulty || 0,
            weight: tdoc.score?.[pid] ?? 100,
            statement: k === 'objective' ? '' : cut(statement, STATEMENT_CAP),
            questions: k === 'objective' ? objectiveQuestionsOf(aiTutor.resolveStatement(pd, 'en'), cfg) : [],
        });
    }
    const taskOf = new Map(tasks.map((t) => [t.pid, t]));
    const objectivePids = tasks.filter((t) => t.kind === 'objective').map((t) => t.pid);

    // ---- who counts: attending students minus staff ----
    const staff = new Set<number>([tdoc.owner, ...(tdoc.maintainer || [])].filter((x) => typeof x === 'number'));
    const tsdocs = await contest.getMultiStatus(domainId, { docId: tdoc.docId }).limit(MAX_STUDENTS + 50).toArray() as any[];
    const statusOf = new Map<number, any>(tsdocs.filter((t) => !staff.has(t.uid)).map((t) => [t.uid, t]));

    // ---- every judged submission of the activity ----
    const recs = await record.getMulti(domainId, {
        contest: tdoc.docId, pid: { $in: pids }, status: { $nin: NONFINAL_STATUS },
    }).project({
        uid: 1, pid: 1, status: 1, score: 1, lang: 1,
    }).sort({ _id: 1 }).limit(MAX_RECORDS).toArray() as any[];
    const submitters = [...new Set(recs.map((r) => r.uid as number).filter((u) => !staff.has(u)))];
    const uids = [...new Set([...submitters, ...[...statusOf.keys()].filter((u) => statusOf.get(u)?.attend)])].sort((a, b) => a - b).slice(0, MAX_STUDENTS);
    const uidSet = new Set(uids);
    const sOf = new Map<number, string>();
    uids.forEach((uid, i) => sOf.set(uid, `S${i + 1}`));

    const cells = new Map<string, Cell>();
    const cellKey = (uid: number, pid: number) => `${uid}:${pid}`;
    const endAt: Date | null = tdoc.endAt ? new Date(tdoc.endAt) : null;
    const beginAt: Date | null = tdoc.beginAt ? new Date(tdoc.beginAt) : null;
    const timeline = new Map<string, { count: number, late: number }>();
    const langs: Record<string, number> = {};
    let lateSubs = 0;
    const lateStudents = new Set<number>();
    for (const r of recs) {
        if (!uidSet.has(r.uid)) continue;
        const at = r._id.getTimestamp();
        const k = cellKey(r.uid, r.pid);
        if (!cells.has(k)) {
            cells.set(k, {
                attempts: [], firstAt: null, acAt: null, acRid: null, lastFailRid: null, lastFailStatus: 0, best: null,
            });
        }
        const c = cells.get(k)!;
        if (!c.firstAt) c.firstAt = at;
        c.attempts.push({
            status: r.status, score: r.score || 0, at, rid: r._id, lang: r.lang || '',
        });
        if (!c.best || (r.score || 0) > c.best.score) c.best = { score: r.score || 0, rid: r._id, at };
        if (r.status === STATUS.STATUS_ACCEPTED) {
            if (!c.acAt) {
                c.acAt = at;
                c.acRid = r._id;
            }
        } else if (!c.acAt) {
            c.lastFailRid = r._id;
            c.lastFailStatus = r.status;
        }
        const day = at.toISOString().slice(0, 10);
        if (!timeline.has(day)) timeline.set(day, { count: 0, late: 0 });
        timeline.get(day)!.count += 1;
        if (endAt && at > endAt) {
            timeline.get(day)!.late += 1;
            lateSubs += 1;
            lateStudents.add(r.uid);
        }
        const t = taskOf.get(r.pid);
        if (t && t.kind === 'programming' && r.lang) {
            const base = String(r.lang).split('.')[0];
            const name = setting.langs?.[r.lang]?.display || setting.langs?.[base]?.display || base;
            langs[name] = (langs[name] || 0) + 1;
        }
    }

    // ---- objective answer sheets (small YAML documents; the best attempt per student) ----
    const answerOf = new Map<string, Record<string, string[]>>(); // cellKey → answers
    if (objectivePids.length) {
        const wanted: any[] = [];
        for (const [k, c] of cells) {
            const pid = +k.split(':')[1];
            if (objectivePids.includes(pid) && c.best) wanted.push(c.best.rid);
        }
        for (let i = 0; i < wanted.length; i += 500) {
            const docs = await record.getMulti(domainId, { _id: { $in: wanted.slice(i, i + 500) } }).project({ uid: 1, pid: 1, code: 1 }).limit(501).toArray() as any[];
            for (const d of docs) answerOf.set(cellKey(d.uid, d.pid), parseAnswerSheet(d.code));
        }
    }

    // ---- code of the accepted (or last failing) attempt on programming tasks ----
    const codeOf = new Map<string, string>();
    if (!light) {
        const wanted: { rid: any, cap: number }[] = [];
        for (const [k, c] of cells) {
            const pid = +k.split(':')[1];
            if (taskOf.get(pid)?.kind !== 'programming') continue;
            if (c.acRid) wanted.push({ rid: c.acRid, cap: CODE_AC_CAP });
            else if (c.lastFailRid) wanted.push({ rid: c.lastFailRid, cap: CODE_FAIL_CAP });
        }
        const capOf = new Map(wanted.map((w) => [String(w.rid), w.cap]));
        for (let i = 0; i < wanted.length; i += 500) {
            const docs = await record.getMulti(domainId, { _id: { $in: wanted.slice(i, i + 500).map((w) => w.rid) } }).project({ code: 1 }).limit(501).toArray() as any[];
            for (const d of docs) codeOf.set(String(d._id), String(d.code || '').slice(0, capOf.get(String(d._id)) || CODE_FAIL_CAP));
        }
    }

    // ---- subjective hand-ins ----
    const handIn = new Map<string, { files: number, words: number, at: Date | null }>();
    for (const t of tasks) {
        if (t.kind !== 'subjective') continue;
        const docs = await listSubjective(domainId, t.pid).catch(() => []);
        for (const d of docs as any[]) {
            if (!uidSet.has(d.uid)) continue;
            handIn.set(cellKey(d.uid, t.pid), { files: (d.files || []).length, words: String(d.report || '').split(/\s+/).filter((x: string) => x).length, at: d.updateAt || null });
        }
    }

    // ---- per-task statistics ----
    const perTask = tasks.map((t) => {
        const own = uids.map((uid) => cells.get(cellKey(uid, t.pid))).filter((c): c is Cell => !!c);
        const verdicts: Record<string, number> = {};
        const firstFail: Record<string, number> = {};
        const minutesToAc: number[] = [];
        let thrashers = 0;
        let solved = 0;
        const bestScores: number[] = [];
        for (const c of own) {
            for (const a of c.attempts) if (a.status !== STATUS.STATUS_ACCEPTED) verdicts[verdictOf(a.status)] = (verdicts[verdictOf(a.status)] || 0) + 1;
            const f = c.attempts[0];
            if (f && f.status !== STATUS.STATUS_ACCEPTED) firstFail[verdictOf(f.status)] = (firstFail[verdictOf(f.status)] || 0) + 1;
            if (c.acAt && c.firstAt) minutesToAc.push(Math.round((c.acAt.getTime() - c.firstAt.getTime()) / 60000));
            if (c.acAt || (c.best && c.best.score >= 100)) solved += 1;
            bestScores.push(c.best ? Math.min(100, c.best.score) : 0);
            if (c.attempts.length >= 3) {
                let fast = 0;
                for (let i = 1; i < c.attempts.length; i++) if (c.attempts[i].at.getTime() - c.attempts[i - 1].at.getTime() < 90000) fast++;
                if (fast / (c.attempts.length - 1) >= 0.5) thrashers++;
            }
        }
        // Objective: accuracy per question and the distribution of the answers given.
        const questions = t.kind === 'objective' ? t.questions.map((q) => {
            const dist: Record<string, number> = {};
            let correct = 0;
            let answered = 0;
            for (const uid of uids) {
                const sheet = answerOf.get(cellKey(uid, t.pid));
                if (!sheet) continue;
                const given = sheet[q.key] || [];
                if (!given.length) continue;
                answered += 1;
                const shown = given.join(',');
                dist[shown] = (dist[shown] || 0) + 1;
                if (q.answer.length && sameSet(given, q.answer)) correct += 1;
            }
            const wrong = Object.entries(dist).filter(([k]) => !q.answer.length || !sameSet(k.split(','), q.answer)).sort((a, b) => b[1] - a[1]).slice(0, 4);
            return {
                key: q.key, kind: q.kind, prompt: q.prompt, answer: q.answer, answered, correct, accuracy: pct(correct, answered), distribution: dist, commonWrong: wrong.map(([k, v]) => ({ answer: k, count: v })),
            };
        }) : [];
        const handed = t.kind === 'subjective' ? uids.filter((uid) => handIn.has(cellKey(uid, t.pid))).length : 0;
        return {
            pid: t.pid,
            label: t.label,
            title: t.title,
            kind: t.kind,
            sub: t.sub || null,
            weight: t.weight,
            points: t.points,
            attempted: own.length,
            solved,
            meanScore: mean1(bestScores),
            medianAttempts: median(own.map((c) => c.attempts.length)),
            maxAttempts: Math.max(0, ...own.map((c) => c.attempts.length)),
            medianMinutesToAc: median(minutesToAc),
            thrashers,
            verdicts,
            firstFail,
            questions,
            accuracy: questions.length ? Math.round(questions.reduce((a, q) => a + q.accuracy, 0) / questions.length) : null,
            handedIn: handed,
        };
    });

    // ---- per knowledge point ----
    const perPoint = new Map<string, any>();
    for (const t of tasks) {
        const pt = perTask.find((x) => x.pid === t.pid)!;
        t.points.forEach((name, i) => {
            const k = name.toLowerCase();
            if (!perPoint.has(k)) perPoint.set(k, { name, path: t.pointPaths[i] || name, tasks: [], attempted: 0, solved: 0, scores: [] as number[] });
            const e = perPoint.get(k);
            e.tasks.push(t.label);
            e.attempted += pt.attempted;
            e.solved += pt.solved;
            if (typeof pt.meanScore === 'number') e.scores.push(pt.meanScore);
        });
    }
    const perPointRows = [...perPoint.values()].map((e) => ({
        name: e.name, path: e.path, tasks: e.tasks, attempted: e.attempted, solved: e.solved, solvedRate: pct(e.solved, e.attempted), meanScore: mean1(e.scores),
    })).sort((a, b) => a.solvedRate - b.solvedRate);

    // ---- scoreboard ----
    const scoreOf = (uid: number) => {
        const ts = statusOf.get(uid);
        if (!ts) return null;
        const v = typeof ts.penaltyScore === 'number' ? ts.penaltyScore : ts.score;
        return typeof v === 'number' ? Math.round(v * 10) / 10 : null;
    };
    const fullScore: number = (Object.values(tdoc.score || {}) as any[]).reduce((a: number, b: any) => a + (+b || 0), 0) || (tasks.length * 100);
    const scores = uids.map(scoreOf).filter((x): x is number => typeof x === 'number');
    const sorted = [...scores].sort((a, b) => b - a);
    const rankOf = new Map<number, number>();
    for (const uid of uids) {
        const s = scoreOf(uid);
        if (typeof s === 'number') rankOf.set(uid, sorted.indexOf(s) + 1);
    }
    const buckets = 10;
    const histogram = Array.from({ length: buckets }, (_, i) => ({ from: Math.round((i * fullScore) / buckets), to: Math.round(((i + 1) * fullScore) / buckets), count: 0 }));
    for (const s of scores) {
        const idx = Math.min(buckets - 1, Math.max(0, Math.floor((s / (fullScore || 1)) * buckets)));
        histogram[idx].count += 1;
    }
    const q = (p: number) => (scores.length ? [...scores].sort((a, b) => a - b)[Math.min(scores.length - 1, Math.floor(p * scores.length))] : 0);
    const enrolled = [...statusOf.values()].filter((t) => t.attend).length;
    const neverSubmitted = uids.filter((uid) => !submitters.includes(uid));

    // ---- timeline ----
    const days = [...timeline.entries()].sort((a, b) => a[0].localeCompare(b[0])).map(([day, v]) => ({ day, count: v.count, late: v.late }));
    const last24h = endAt ? recs.filter((r) => uidSet.has(r.uid) && endAt.getTime() - r._id.getTimestamp().getTime() <= 86400000 && r._id.getTimestamp() <= endAt).length : 0;

    const lightStats = {
        activity: tdoc.title,
        kind,
        participants: uids.length,
        submitters: submitters.length,
        enrolled,
        neverSubmitted: neverSubmitted.length,
        records: recs.length,
        sampled: pidsAll.length > pids.length || recs.length >= MAX_RECORDS || uids.length >= MAX_STUDENTS,
        beginAt: beginAt ? beginAt.toISOString() : null,
        endAt: endAt ? endAt.toISOString() : null,
        late: { submissions: lateSubs, students: lateStudents.size, last24h },
        problems: perTask.map((p) => ({
            label: p.label, title: p.title, kind: p.kind, sub: p.sub, weight: p.weight, attempted: p.attempted, solved: p.solved, meanScore: p.meanScore, medianAttempts: p.medianAttempts, maxAttempts: p.maxAttempts, thrashers: p.thrashers, verdicts: p.verdicts, firstFail: p.firstFail, accuracy: p.accuracy, handedIn: p.handedIn,
            questions: p.questions.map((qq) => ({ key: qq.key, accuracy: qq.accuracy, answered: qq.answered, answer: qq.answer, commonWrong: qq.commonWrong })),
        })),
        scores: {
            students: scores.length, full: fullScore, mean: mean1(scores), median: median(scores), min: scores.length ? Math.min(...scores) : 0, max: scores.length ? Math.max(...scores) : 0, q1: q(0.25), q3: q(0.75), histogram,
        },
        timeline: days,
        points: perPointRows.slice(0, 16),
        languages: langs,
    };

    // ---- the per-student corpus (full mode) ----
    const students: any[] = [];
    let udict: any = {};
    if (!light) {
        udict = await user.getList(domainId, uids).catch(() => ({}));
        for (const uid of uids) {
            const st: any = {
                uid, s: sOf.get(uid), uname: udict[uid]?.uname || `user#${uid}`, score: scoreOf(uid), rank: rankOf.get(uid) || null, late: lateStudents.has(uid), attended: !!statusOf.get(uid)?.attend, tasks: [] as any[],
            };
            for (const t of tasks) {
                const c = cells.get(cellKey(uid, t.pid));
                if (t.kind === 'subjective') {
                    const h = handIn.get(cellKey(uid, t.pid));
                    st.tasks.push({ label: t.label, kind: t.kind, handedIn: !!h, files: h?.files || 0, words: h?.words || 0 });
                    continue;
                }
                if (!c) {
                    st.tasks.push({ label: t.label, kind: t.kind, attempts: [], solved: false, best: null });
                    continue;
                }
                const t0 = c.firstAt ? c.firstAt.getTime() : 0;
                const attempts = c.attempts.map((a, i) => `#${i + 1} ${verdictOf(a.status)}${a.score ? `(${a.score})` : ''}@+${Math.round((a.at.getTime() - t0) / 60000)}m${endAt && a.at > endAt ? ' LATE' : ''}`);
                const entry: any = {
                    label: t.label, kind: t.kind, attempts, solved: !!c.acAt || (!!c.best && c.best.score >= 100), best: c.best ? c.best.score : 0, minutesToAc: c.acAt && c.firstAt ? Math.round((c.acAt.getTime() - c.firstAt.getTime()) / 60000) : null,
                };
                if (t.kind === 'programming') {
                    entry.lang = c.attempts[c.attempts.length - 1]?.lang || '';
                    entry.code = c.acRid ? { kind: 'accepted', text: codeOf.get(String(c.acRid)) || '' } : c.lastFailRid ? { kind: `last failing (${verdictOf(c.lastFailStatus)})`, text: codeOf.get(String(c.lastFailRid)) || '' } : null;
                } else {
                    const sheet = answerOf.get(cellKey(uid, t.pid)) || {};
                    entry.answers = t.questions.map((qq) => {
                        const given = sheet[qq.key] || [];
                        return { key: qq.key, given, correct: qq.answer.length ? sameSet(given, qq.answer) : null, answer: qq.answer };
                    });
                }
                st.tasks.push(entry);
            }
            students.push(st);
        }
    }
    return {
        tdoc, kind, tasks, uids, sOf, udict, perTask, perPoint: perPointRows, light: lightStats, students, neverSubmitted, staff: [...staff],
    };
}

/* ------------------------------ rendering ------------------------------ */

/** The task list as the model reads it (both stages): kinds, points, statements, answer keys. */
export function activityTaskBlock(corpus: any): string {
    const L: string[] = [`=== TASKS OF THE ${String(corpus.kind).toUpperCase()} "${corpus.tdoc.title}" (${corpus.tasks.length}) ===`];
    for (const t of corpus.tasks as ActivityTask[]) {
        const head = `${t.label} [${t.kind}${t.sub ? `/${t.sub}` : ''}] "${t.title}" — weight ${t.weight} pts${t.difficulty ? `, difficulty ${t.difficulty}/10` : ''} — knowledge points: ${t.pointPaths.length ? t.pointPaths.join('; ') : '(unlabeled)'}`;
        L.push(head);
        if (t.kind === 'objective') {
            for (const q of t.questions) {
                const opts = q.options.length ? ` options: ${q.options.map((o) => `${o.letter}) ${o.text}`).join(' | ')}` : '';
                L.push(`  Q${q.key} (${q.kind}): ${q.prompt || '(see statement)'}${opts} — KEY: ${q.answer.join(',') || '?'}`);
            }
        } else if (t.statement) {
            L.push(`  statement: ${oneLine(t.statement)}`);
        }
    }
    L.push('=== END TASKS ===');
    return L.join('\n');
}

function renderAttempts(attempts: string[], collapse: boolean): string {
    if (!collapse || attempts.length <= 8) return attempts.join(' → ');
    const v = (a: string) => a.replace(/^#\d+\s*/, '').replace(/@\+\d+m( LATE)?$/, '');
    const out: string[] = [];
    let i = 0;
    while (i < attempts.length) {
        let j = i;
        while (j + 1 < attempts.length && v(attempts[j + 1]) === v(attempts[i])) j++;
        if (j - i >= 2) out.push(`${attempts[i]} … ${attempts[j]} (${j - i + 1}× ${v(attempts[i])})`);
        else for (let k = i; k <= j; k++) out.push(attempts[k]);
        i = j + 1;
    }
    return out.join(' → ');
}

/** One student's transcript at a compaction level, optionally restricted to some tasks. */
export function renderActivityStudent(st: any, level: number, taskLabels?: string[], part?: { i: number, n: number }): string {
    const lv = LEVELS[Math.min(level, LEVELS.length - 1)];
    const L: string[] = ['', `--- ${st.s}${part ? ` (part ${part.i}/${part.n}: tasks ${taskLabels!.join(', ')})` : ''} ---`,
        `score ${st.score ?? '?'}${st.rank ? ` (rank ${st.rank})` : ''}${st.late ? ' | submitted late' : ''}${!st.attended ? ' | not enrolled (submitted anyway)' : ''}`];
    for (const t of st.tasks) {
        if (taskLabels && !taskLabels.includes(t.label)) continue;
        if (t.kind === 'subjective') {
            L.push(`${t.label} [subjective]: ${t.handedIn ? `handed in — ${t.files} file(s), ${t.words} words of report` : 'NOT handed in'}`);
            continue;
        }
        if (!t.attempts.length) {
            L.push(`${t.label}: (no submissions)`);
            continue;
        }
        if (t.kind === 'programming') {
            L.push(`${t.label} [programming${t.lang ? `, ${t.lang}` : ''}]: ${renderAttempts(t.attempts, lv.collapse)}${t.solved ? ` — solved after ${t.minutesToAc} min` : ` — NOT solved (best ${t.best})`}`);
            if (t.code && t.code.text) {
                let code = t.code.text.slice(0, lv.code);
                if (lv.collapse) code = code.split('\n').filter((l: string) => l.trim() && !/^\s*(?:\/\/|#)/.test(l)).join('\n');
                L.push(`  code (${t.code.kind}):`, ...code.split('\n').map((l: string) => `    ${l.replace(/^\t+/, '    ')}`));
            }
        } else {
            const parts = (t.answers || [])
                .filter((a: any) => !lv.wrongOnly || a.correct === false || !a.given.length)
                .map((a: any) => `Q${a.key}: ${a.given.length ? a.given.join(',') : '(blank)'}${a.correct === true ? ' ✓' : a.correct === false ? ` ✗ (key ${a.answer.join(',')})` : ''}`);
            const right = (t.answers || []).filter((a: any) => a.correct === true).length;
            L.push(`${t.label} [objective]: ${t.attempts.length} submission(s), best ${t.best} — ${right}/${(t.answers || []).length} correct${parts.length ? ` — ${parts.join('; ')}` : lv.wrongOnly ? ' — all correct' : ''}`);
        }
    }
    return L.join('\n');
}

interface MapItem { st: any, level: number, tasks?: string[], part?: { i: number, n: number }, text: string }

/** Pack students into batches by size (first-fit decreasing); split an oversized student by task. */
function packBatches(students: any[], budget: number, overhead: number, maxCalls = MAX_CALLS()): { batches: MapItem[][], parts: number, startLevel: number } {
    // 📏 Every call carries the task block (statements, options, keys —
    // easily 10k+ characters for a 30-question paper) plus framing; the
    // students get what is left, never less than 40% of the budget.
    const headroom = Math.max(Math.floor(budget * 0.4), budget - overhead - 600);
    const totalAt = (level: number) => students.reduce((n, st) => n + renderActivityStudent(st, level).length, 0);
    let startLevel = 0;
    while (startLevel < LEVELS.length - 1 && Math.ceil(totalAt(startLevel) / headroom) > maxCalls) startLevel += 1;
    const items: MapItem[] = [];
    let parts = 0;
    for (const st of students) {
        let placed = false;
        for (let level = startLevel; level < LEVELS.length; level++) {
            const text = renderActivityStudent(st, level);
            if (text.length <= headroom) {
                items.push({ st, level, text });
                placed = true;
                break;
            }
        }
        if (placed) continue;
        const level = LEVELS.length - 1;
        const groups: string[][] = [];
        let cur: string[] = [];
        for (const t of st.tasks) {
            const trial = renderActivityStudent(st, level, [...cur, t.label]);
            if (cur.length && trial.length > headroom) {
                groups.push(cur);
                cur = [t.label];
            } else cur.push(t.label);
        }
        if (cur.length) groups.push(cur);
        groups.forEach((g, i) => {
            const part = { i: i + 1, n: groups.length };
            let text = renderActivityStudent(st, level, g, part);
            if (text.length > headroom) text = `${text.slice(0, headroom - 40)}\n    … (truncated to fit the analysis budget)`;
            items.push({ st, level, tasks: g, part, text });
        });
        parts += groups.length;
    }
    items.sort((a, b) => b.text.length - a.text.length);
    const batches: { items: MapItem[], size: number }[] = [];
    for (const it of items) {
        const home = batches.find((b) => b.size + it.text.length <= headroom);
        if (home) {
            home.items.push(it);
            home.size += it.text.length;
        } else batches.push({ items: [it], size: it.text.length });
    }
    return { batches: batches.map((b) => b.items), parts, startLevel };
}

function batchContext(corpus: any, items: MapItem[]): string {
    return [activityTaskBlock(corpus), '', `=== STUDENTS IN THIS BATCH (${items.length} block(s)) — complete records ===`, ...items.map((it) => it.text), '', '=== END BATCH. Reply with the JSON. ==='].join('\n');
}

function parseMap(raw: string, tokens: Set<string>, labels: Set<string>, points: Map<string, string>) {
    let j: any;
    try {
        j = JSON.parse(raw.replace(/^```(?:json)?\s*|\s*```$/g, '').trim());
    } catch (e) {
        const m = raw.match(/\{[\s\S]*\}/);
        if (!m) throw new Error('map reply is not JSON');
        j = JSON.parse(m[0]);
    }
    const tok = (x: any) => (tokens.has(String(x)) ? String(x) : null);
    const pointName = (x: any) => points.get(String(x || '').toLowerCase()) || String(x || '').slice(0, 60);
    const students = (Array.isArray(j?.students) ? j.students : []).map((s: any) => ({
        s: tok(s?.s),
        summary: String(s?.summary || '').slice(0, 400),
        struggles: (Array.isArray(s?.struggles) ? s.struggles : []).slice(0, 6).map((x: any) => ({ concept: pointName(x?.concept), evidence: String(x?.evidence || '').slice(0, 200) })),
        level: ['strong', 'middle', 'weak', 'absent'].includes(s?.level) ? s.level : 'middle',
        attention: !!s?.attention,
        reason: String(s?.reason || '').slice(0, 200),
    })).filter((s: any) => s.s);
    const errors = (Array.isArray(j?.errors) ? j.errors : []).map((e: any) => ({
        category: String(e?.category || '').slice(0, 80),
        concept: pointName(e?.concept),
        kind: e?.kind === 'objective' ? 'objective' : 'programming',
        tasks: (Array.isArray(e?.tasks) ? e.tasks : []).map(String).filter((l: string) => labels.has(l)),
        students: (Array.isArray(e?.students) ? e.students : []).map(tok).filter((x: any) => x),
        evidence: String(e?.evidence || '').slice(0, 240),
    })).filter((e: any) => e.category && e.students.length);
    const misconceptions = (Array.isArray(j?.misconceptions) ? j.misconceptions : []).map((m: any) => ({
        task: labels.has(String(m?.task)) ? String(m.task) : '',
        question: String(m?.question || '').slice(0, 12),
        chosen: String(m?.chosen || '').slice(0, 40),
        students: (Array.isArray(m?.students) ? m.students : []).map(tok).filter((x: any) => x),
        reveals: String(m?.reveals || '').slice(0, 240),
    })).filter((m: any) => m.task && m.students.length);
    const notes = (Array.isArray(j?.notes) ? j.notes : []).map((x: any) => String(x).slice(0, 240)).slice(0, 3);
    return { students, errors, misconceptions, notes };
}

/** REDUCE context: the statistics + the merged findings, trimmed to the budget. */
export function activityReportContext(corpus: any, findings: any): string {
    const L = corpus.light;
    const out: string[] = [`=== ${String(corpus.kind).toUpperCase()}: "${corpus.tdoc.title}" — ${L.participants} students (${L.enrolled} enrolled, ${L.submitters} submitted, ${L.neverSubmitted} never submitted), ${corpus.tasks.length} tasks, ${L.records} judged submissions ===`];
    if (L.beginAt || L.endAt) out.push(`Window: ${L.beginAt || '?'} → ${L.endAt || '?'} (deadline). Late submissions: ${L.late.submissions} by ${L.late.students} student(s); ${L.late.last24h} submissions in the last 24 h before the deadline.`);
    out.push(activityTaskBlock(corpus), '');
    out.push('=== SCORES (scoreboard, deterministic) ===');
    const S = L.scores;
    out.push(`full score ${S.full}; students scored ${S.students}; mean ${S.mean ?? '-'}, median ${S.median}, Q1 ${S.q1}, Q3 ${S.q3}, min ${S.min}, max ${S.max}`);
    out.push(`histogram: ${S.histogram.map((h: any) => `[${h.from}-${h.to}) ${h.count}`).join(' | ')}`);
    out.push('', '=== PER-TASK STATISTICS (deterministic; the ONLY numbers you may cite) ===');
    for (const p of corpus.perTask) {
        if (p.kind === 'subjective') {
            out.push(`${p.label} [subjective] "${p.title}": handed in by ${p.handedIn} of ${L.participants}`);
            continue;
        }
        out.push(`${p.label} [${p.kind}] "${p.title}": attempted ${p.attempted}, solved ${p.solved}, mean best score ${p.meanScore ?? '-'}/100, median attempts ${p.medianAttempts}, max ${p.maxAttempts}${p.kind === 'programming' ? `, median minutes to accept ${p.medianMinutesToAc}, grader-thrash students ${p.thrashers}` : ''}`);
        if (p.kind === 'programming') {
            out.push(`  failing verdicts (all attempts): ${Object.entries(p.verdicts).map(([k, v]) => `${k}=${v}`).join(', ') || '(none)'}; first-attempt verdicts: ${Object.entries(p.firstFail).map(([k, v]) => `${k}=${v}`).join(', ') || '(none)'}`);
        } else {
            for (const qq of p.questions) {
                const dist = Object.entries(qq.distribution).sort((a: any, b: any) => b[1] - a[1]).slice(0, 6).map(([k, v]) => `${k}:${v}`).join(' ');
                out.push(`  Q${qq.key}: ${qq.correct}/${qq.answered} correct (${qq.accuracy}%) — key ${qq.answer.join(',') || '?'} — answers given: ${dist || '(none)'}`);
            }
        }
    }
    out.push('', '=== PER-KNOWLEDGE-POINT STATISTICS ===');
    for (const e of corpus.perPoint) out.push(`${e.path}: tasks ${e.tasks.join(', ')}; solved rate ${e.solvedRate}% (${e.solved}/${e.attempted} task-attempts); mean best score ${e.meanScore ?? '-'}`);
    if (!corpus.perPoint.length) out.push('(no knowledge points are attached to the tasks)');
    out.push('', `=== SUBMISSION TIMELINE (per day) === ${L.timeline.map((d: any) => `${d.day}: ${d.count}${d.late ? ` (${d.late} late)` : ''}`).join(' | ') || '(none)'}`);
    if (Object.keys(L.languages).length) out.push(`languages used: ${Object.entries(L.languages).map(([k, v]) => `${k}=${v}`).join(', ')}`);
    const cov = findings.coverage || { students: corpus.uids.length, analyzed: corpus.uids.length, cached: 0, unanalyzed: [] as string[] };
    out.push('', `=== FINDINGS OF THE PER-STUDENT ANALYSIS (${cov.analyzed} of ${cov.students} students read individually — every submission, every answer${cov.cached ? `; ${cov.cached} unchanged since the last report, reused` : ''}) ===`);
    if (cov.unanalyzed.length) out.push(`NOTE: ${cov.unanalyzed.length} student(s) could NOT be analyzed individually and appear in the statistics only: ${cov.unanalyzed.join(', ')}. Say so in section 1.`);
    else out.push('Every participating student was analyzed individually.');
    out.push('--- classified errors (merged across students) ---');
    for (const e of findings.errors) out.push(`- [${e.kind}] [${e.concept}] ${e.category}: ${e.students.length} student(s) (${e.students.slice(0, 20).join(', ')}${e.students.length > 20 ? ', …' : ''}) on ${e.tasks.join(', ') || '?'} — ${e.evidence}`);
    if (findings.misconceptions.length) {
        out.push('--- objective-question misconceptions (what the wrong choices reveal) ---');
        for (const m of findings.misconceptions) out.push(`- ${m.task} Q${m.question}, chose ${m.chosen}: ${m.students.length} student(s) (${m.students.slice(0, 20).join(', ')}) — ${m.reveals}`);
    }
    const attention = findings.students.filter((x: any) => x.attention);
    const rest = findings.students.filter((x: any) => !x.attention);
    const groups: Record<string, string[]> = { strong: [], middle: [], weak: [], absent: [] };
    for (const x of rest) (groups[x.level] || groups.middle).push(x.s);
    const line = (x: any, full: boolean) => `${x.s}: level=${x.level}${x.attention ? ` ATTENTION (${x.reason})` : ''} — ${full ? x.summary : x.summary.slice(0, 160)}${x.struggles.length ? ` | struggles: ${x.struggles.slice(0, full ? 6 : 3).map((y: any) => `${y.concept}${full ? ` (${y.evidence})` : ''}`).join('; ')}` : ''}`;
    const build = (tier: number) => {
        const b: string[] = ['--- students needing attention ---', ...attention.map((x: any) => line(x, tier === 0))];
        b.push('--- other students, by level (every token listed) ---');
        for (const [g, toks] of Object.entries(groups)) if (toks.length) b.push(`${g}: ${toks.join(', ')}`);
        if (tier <= 1) b.push('--- their summaries ---', ...rest.map((x: any) => line(x, false)));
        if (findings.notes.length) b.push('--- batch notes ---', ...findings.notes.map((n: string) => `- ${n}`));
        return b;
    };
    const budget = REDUCE_CHARS();
    const head = out.join('\n').length;
    let tier = 0;
    let body = build(tier);
    while (tier < 2 && head + body.join('\n').length > budget) {
        tier += 1;
        body = build(tier);
    }
    out.push(...body);
    out.push('', '=== End of context. Write the report now. ===');
    return out.join('\n');
}

/**
 * PTA fork — the json:remedial trailer (one Studio brief per concept),
 * extracted and stripped from the prose like json:concepts. Tolerant by
 * design: a missing or unparsable block yields [] and the report stands —
 * the prompts are an enhancement to the report, never a condition of it.
 * Student tokens and task labels are validated against the corpus so a
 * hallucinated "S99" or "P42" cannot reach the teacher's cards.
 */
export function extractRemedialBlock(md: string, validLabels?: Set<string>, validTokens?: Set<string>): { report: string, remedial: any[] } {
    const m = md.match(/```json:remedial[ \t]*\n([\s\S]*?)```/);
    if (!m) return { report: md.trim(), remedial: [] };
    const report = (md.slice(0, m.index) + md.slice((m.index as number) + m[0].length)).trim();
    let remedial: any[] = [];
    try {
        const parsed = JSON.parse(m[1]);
        // Remedial practice is always a code task; a quiz answer from an
        // older prompt (or a stray value) becomes a programming task.
        const KINDS = ['programming', 'function'];
        const DIFFS = ['intro', 'medium', 'challenge'];
        if (Array.isArray(parsed?.remedial)) {
            remedial = parsed.remedial
                .filter((r: any) => r && typeof r.concept === 'string' && typeof r.brief === 'string' && r.brief.trim())
                .slice(0, 8)
                .map((r: any) => ({
                    concept: String(r.concept).slice(0, 60),
                    kind: KINDS.includes(r.kind) ? r.kind : 'programming',
                    difficulty: DIFFS.includes(r.difficulty) ? r.difficulty : 'intro',
                    title: String(r.title || r.concept).slice(0, 80),
                    brief: String(r.brief).slice(0, 2000),
                    avoid: (Array.isArray(r.avoid) ? r.avoid : []).map(String).filter((l: string) => !validLabels || validLabels.has(l)).slice(0, 12),
                    students: (Array.isArray(r.students) ? r.students : []).map(String).filter((t: string) => !validTokens || validTokens.has(t)).slice(0, 200),
                }));
        }
    } catch (e) {
        logger.warn('[activity-report] remedial block unparsable: %s', e.message);
    }
    return { report, remedial };
}

/** The mandatory json:concepts trailer, extracted and stripped from the prose. */
export function extractConceptBlock(md: string, validLabels?: Set<string>): { report: string, concepts: any[] } {
    const m = md.match(/```json:concepts[ \t]*\n([\s\S]*?)```/);
    if (!m) return { report: md.trim(), concepts: [] };
    const report = (md.slice(0, m.index) + md.slice((m.index as number) + m[0].length)).trim();
    let concepts: any[] = [];
    try {
        const parsed = JSON.parse(m[1]);
        if (Array.isArray(parsed?.concepts)) {
            concepts = parsed.concepts
                .filter((c: any) => c && typeof c.name === 'string')
                .slice(0, 10)
                .map((c: any) => ({
                    name: String(c.name).slice(0, 60),
                    problems: Object.fromEntries(Object.entries(c.problems || {})
                        .filter(([k, v]) => Number.isFinite(+(v as any)) && +(v as any) > 0 && (!validLabels || validLabels.has(String(k))))
                        .map(([k, v]) => [String(k).slice(0, 16), Math.round(+(v as any))])),
                    students: Array.isArray(c.students) ? c.students.map(String).slice(0, 100) : [],
                }))
                .filter((c: any) => !validLabels || Object.keys(c.problems).length);
        }
    } catch (e) {
        logger.warn('[activity-report] concepts block unparsable: %s', e.message);
    }
    return { report, concepts };
}

/* ------------------------------ the job ------------------------------ */

/**
 * 📡 The activity report JOB — detached from the request; progress on the
 * report document: collect → map (batches, a few at a time) → reduce →
 * substitute names → store.
 */
export async function runActivityReportJob(domainId: string, tdoc: any, kind: 'homework' | 'contest', by: number): Promise<void> {
    const tid = String(tdoc.docId);
    const startedAt = new Date();
    const progress = (patch: any) => setClassReportJob(domainId, tid, {
        status: 'running', stage: 'collect', done: 0, total: 0, startedAt, by, ...patch,
    });
    try {
        await progress({ stage: 'collect' });
        const corpus = await buildActivityCorpus(domainId, tdoc, kind, false);
        if (!corpus.light.records) throw new Error('No judged submissions yet — nothing to analyze.');
        const tokens = new Set<string>([...corpus.sOf.values()]);
        const labels = new Set<string>(corpus.tasks.map((t) => t.label));
        const pointNames = new Map<string, string>();
        for (const t of corpus.tasks) for (const n of t.points) pointNames.set(String(n).toLowerCase(), String(n));

        // 🗂 Unchanged students come from the cache of the previous run.
        const hashOf = new Map<number, string>();
        for (const st of corpus.students) hashOf.set(st.uid, createHash('sha1').update(renderActivityStudent(st, 0)).digest('hex'));
        const cache = await getClassReportMapCache(domainId, tid, corpus.uids);
        const perStudent = new Map<string, any>();
        const analyzedNow = new Set<string>();
        const cachedNow = new Set<string>();
        const fresh: any[] = [];
        for (const st of corpus.students) {
            const c = cache.get(st.uid);
            if (c && c.hash === hashOf.get(st.uid) && c.findings) {
                perStudent.set(st.s, { ...c.findings, s: st.s });
                cachedNow.add(st.s);
            } else fresh.push(st);
        }
        const budget = BATCH_CHARS();
        const taskBlock = activityTaskBlock(corpus);
        const { batches, parts, startLevel } = packBatches(fresh, budget, taskBlock.length);
        logger.info('[activity-report] %s/%s: %d fresh student(s) → %d call(s) at level %d (%d-char budget)%s', domainId, tid, fresh.length, batches.length, startLevel, budget, parts ? `; ${parts} part(s) split by task` : '');
        await progress({
            stage: 'map', done: 0, total: batches.length, students: corpus.uids.length, analyzed: cachedNow.size, cached: cachedNow.size,
        });

        const errByKey = new Map<string, any>();
        const misByKey = new Map<string, any>();
        const notes: string[] = [];
        const absorb = (r: any, items: MapItem[]) => {
            const inBatch = new Set(items.map((it) => it.st.s));
            for (const sx of r.students) {
                if (!inBatch.has(sx.s)) continue;
                const prev = perStudent.get(sx.s);
                if (!prev) perStudent.set(sx.s, sx);
                else {
                    prev.summary = prev.summary.length >= sx.summary.length ? prev.summary : sx.summary;
                    for (const g of sx.struggles) if (!prev.struggles.some((x: any) => x.concept === g.concept)) prev.struggles.push(g);
                    prev.attention = prev.attention || sx.attention;
                    if (sx.attention && !prev.reason) prev.reason = sx.reason;
                    const rank = ['absent', 'weak', 'middle', 'strong'];
                    prev.level = rank[Math.max(rank.indexOf(prev.level), rank.indexOf(sx.level))] || prev.level;
                }
                analyzedNow.add(sx.s);
            }
            for (const e of r.errors) {
                const key = `${e.kind}|${e.concept.toLowerCase()}|${e.category.toLowerCase()}`;
                if (!errByKey.has(key)) errByKey.set(key, { ...e, students: [], tasks: [] });
                const m = errByKey.get(key);
                for (const st of e.students) if (!m.students.includes(st)) m.students.push(st);
                for (const t of e.tasks) if (!m.tasks.includes(t)) m.tasks.push(t);
            }
            for (const ms of r.misconceptions) {
                const key = `${ms.task}|${ms.question}|${ms.chosen.toLowerCase()}`;
                if (!misByKey.has(key)) misByKey.set(key, { ...ms, students: [] });
                const m = misByKey.get(key);
                for (const st of ms.students) if (!m.students.includes(st)) m.students.push(st);
                if (ms.reveals.length > m.reveals.length) m.reveals = ms.reveals;
            }
            notes.push(...r.notes);
        };
        let done = 0;
        const analyzeItems = async (items: MapItem[], depth = 0): Promise<void> => {
            /*
             * 🔁 Transient provider errors (rate limits, 5xx, timeouts) are
             * retried with backoff before anything else — at 200 students a
             * 429 burst must not turn into a bisection cascade. A malformed
             * reply gets ONE fresh call (the model is not deterministic);
             * only then is the batch split.
             */
            const ctx = batchContext(corpus, items);
            for (let ask = 0; ask < 2; ask++) {
                try {
                    const raw = await aiTutor.callWithRetry(() => aiTutor.runActivityMapBatch(ctx), { label: `activity map (${items.length} block(s))` });
                    absorb(parseMap(raw, tokens, labels, pointNames), items);
                    return;
                } catch (e) {
                    logger.warn('[activity-report] map call failed (%d block(s), depth %d, ask %d): %s', items.length, depth, ask + 1, e.message);
                    if (aiTutor.isTransientProviderError(e)) break; // retries exhausted: shrink rather than repeat
                }
            }
            if (items.length > 1) {
                const mid = Math.ceil(items.length / 2);
                await analyzeItems(items.slice(0, mid), depth + 1);
                await analyzeItems(items.slice(mid), depth + 1);
                return;
            }
            const it = items[0];
            if (it.level < LEVELS.length - 1) {
                await analyzeItems([{ ...it, level: it.level + 1, text: renderActivityStudent(it.st, it.level + 1, it.tasks, it.part) }], depth + 1);
            }
        };
        let cursor = 0;
        const worker = async () => {
            for (;;) {
                const idx = cursor++;
                if (idx >= batches.length) return;
                await analyzeItems(batches[idx]);
                done += 1;
                await progress({
                    stage: 'map', done, total: batches.length, students: corpus.uids.length, analyzed: analyzedNow.size + cachedNow.size, cached: cachedNow.size,
                });
            }
        };
        await Promise.all(Array.from({ length: MAP_CONCURRENCY() }, () => worker()));
        for (const st of fresh) {
            const f = perStudent.get(st.s);
            if (f && analyzedNow.has(st.s)) await setClassReportMapCache(domainId, tid, st.uid, hashOf.get(st.uid)!, { ...f, s: undefined }).catch(() => {});
        }
        const unanalyzed = corpus.students.map((st: any) => st.s).filter((tok: string) => !perStudent.has(tok));
        const findings = {
            errors: [...errByKey.values()].sort((x, y) => y.students.length - x.students.length).slice(0, 40),
            misconceptions: [...misByKey.values()].sort((x, y) => y.students.length - x.students.length).slice(0, 30),
            students: [...perStudent.values()],
            notes: notes.slice(0, 8),
            coverage: { students: corpus.uids.length, analyzed: analyzedNow.size + cachedNow.size, cached: cachedNow.size, unanalyzed },
        };
        const covPatch = { students: corpus.uids.length, analyzed: findings.coverage.analyzed, cached: cachedNow.size, unanalyzed: unanalyzed.length };
        await progress({ stage: 'reduce', done: batches.length, total: batches.length, ...covPatch });
        const reduceCtx = activityReportContext(corpus, findings);
        const raw = await aiTutor.callWithRetry(() => aiTutor.runActivityReport(reduceCtx), { label: 'activity reduce' });
        await progress({ stage: 'finalize', done: batches.length, total: batches.length, ...covPatch });
        const sidMap = [...corpus.sOf.entries()].map(([uid, sTok]) => ({ s: sTok, uid, uname: corpus.udict[uid]?.uname || `user#${uid}` }));
        const { report: withoutRemedial, remedial: remedialAnon } = extractRemedialBlock(raw, labels, new Set(sidMap.map((e) => e.s)));
        const { report: reportAnon, concepts: conceptsAnon } = extractConceptBlock(withoutRemedial, labels);
        const byTok = new Map(sidMap.map((e) => [e.s, e.uname]));
        const uidByTok = new Map(sidMap.map((e) => [e.s, e.uid]));
        const substitute = (text: string) => text.replace(/\bS(\d+)\b/g, (m) => byTok.get(m) || m);
        const reportNamed = substitute(reportAnon);
        const concepts = conceptsAnon.map((c: any) => ({ ...c, students: (c.students || []).map((tok: string) => byTok.get(tok) || tok) }));
        const remedial = remedialAnon.map((r: any) => ({
            ...r,
            brief: substitute(r.brief),
            students: (r.students || []).map((tok: string) => byTok.get(tok) || tok),
            uids: (r.students || []).map((tok: string) => uidByTok.get(tok)).filter((u: any) => typeof u === 'number'),
        }));
        await setClassReport({
            domainId, tid, reportAnon, reportNamed, sidMap, concepts, remedial, statsSnapshot: corpus.light, participants: corpus.uids.length, generatedBy: by,
        });
        await setClassReportJob(domainId, tid, {
            status: 'done', stage: 'done', done: batches.length, total: batches.length, startedAt, finishedAt: new Date(), by, ...covPatch,
        });
        logger.info('[activity-report] %s/%s generated by uid=%d (%d students: %d analyzed now, %d cached, %d unanalyzed; %d calls)', domainId, tid, by, corpus.uids.length, analyzedNow.size, cachedNow.size, unanalyzed.length, batches.length);
    } catch (e) {
        logger.warn('[activity-report] job for %s/%s failed: %s', domainId, tid, e.message);
        await setClassReportJob(domainId, tid, {
            status: 'failed', stage: 'done', done: 0, total: 0, startedAt, finishedAt: new Date(), error: String(e.message || e).slice(0, 300), by,
        }).catch(() => {});
    }
}
