import { ObjectId } from 'mongodb';
import { load as yamlLoad } from 'js-yaml';
import { STATUS } from '@hydrooj/common';
import { ForbiddenError, HomeworkNotLiveError, NotFoundError } from '../error';
import * as aiTutor from './ai_tutor';
import { objectiveQuestionsOf, parseAnswerSheet, sameSet } from './activity_report';
import { Logger } from '../logger';
import { readRawProblemConfig } from './problem_config';
import { PERM } from '../model/builtin';
import * as contest from '../model/contest';
import KnowledgeModel from '../model/knowledge';
import {
    getObjectiveFeedback, listObjectiveFeedback, objectiveFeedbackJobStale, purgeMalformedObjectiveFeedback,
    setObjectiveFeedbackJob, setObjectiveFeedbackReport,
} from '../model/objective_feedback';
import { getQuick, studentFeedbackVisible } from '../model/quick_review';
import problem from '../model/problem';
import record from '../model/record';
import { Handler, param, Types } from '../service/server';

const logger = new Logger('objective-feedback');

/**
 * PTA fork — AI EXPLANATION OF ONE OBJECTIVE TASK THE STUDENT GOT WRONG.
 *
 * This is a LIBRARY module, not a handler plugin: handler/homework.ts
 * registers the route and the page hook (applyObjectiveFeedback) — Hydro
 * only discovers handler/*.ts files at process start, while an existing
 * handler is hot-reloaded on change, so wiring from homework.ts lets the
 * feature appear without a restart.
 *
 * Once a homework has ENDED (past the late window, i.e. contest.isDone —
 * endAt is the hard deadline), a student who took part gets an "Explain"
 * button NEXT TO EVERY OBJECTIVE TASK they did not get fully right, in
 * their results table. It explains that ONE task: the correct answer, why
 * it is right, what their own answer suggests they misunderstood, a tip,
 * and what to review — in English, whatever language the question is in.
 * Programming tasks are not covered here; they have the per-submission AI
 * Suggestions.
 *
 * What the model reads (collectObjectiveReview, restricted to one task):
 * the task's knowledge points; each question's text, options and ANSWER
 * KEY (from the raw config.yaml, as the judge reads it); the answers from the
 * submission that COUNTS for the homework (tsdoc.detail[pid].rid — the
 * scoreboard's), marked with the judge's own rules (multi-select: full /
 * partial / wrong; blanks honour the task's ignoreCase / ignoreSpaces).
 *
 * Each explanation is generated by a BACKGROUND JOB the page polls (it is
 * stored per task; closing the page does not interrupt it) and kept until
 * the student asks for it again.
 */

const JOB_SILENCE_MS = 5 * 60 * 1000;

interface ReviewQuestion {
    key: string;
    kind: string;
    prompt: string;
    options: { letter: string, text: string }[];
    answer: string[];
    given: string[];
    outcome: 'correct' | 'partial' | 'wrong' | 'unanswered' | 'ungraded';
}

function parseConfig(cfg: any): any {
    if (typeof cfg !== 'string') return cfg && typeof cfg === 'object' ? cfg : null;
    try {
        return yamlLoad(cfg);
    } catch (e) {
        return null;
    }
}

/** The judge's comparison for one question (hydrojudge/src/judge/objective.ts). */
function outcomeOf(q: { kind: string, answer: string[] }, given: string[], matching: any): ReviewQuestion['outcome'] {
    if (!given.length) return 'unanswered';
    if (!q.answer.length) return 'ungraded';
    if (q.kind === 'multiselect') {
        const key = new Set(q.answer);
        const ans = new Set(given);
        if (ans.size === key.size && [...ans].every((x) => key.has(x))) return 'correct';
        if ([...ans].every((x) => key.has(x))) return 'partial';
        return 'wrong';
    }
    if (q.kind === 'select') return sameSet(given, q.answer) ? 'correct' : 'wrong';
    const norm = (s: string) => {
        let t = String(s ?? '').trim();
        if (matching?.ignoreCase) t = t.toLowerCase();
        if (matching?.ignoreSpaces) t = t.replace(/\s+/g, '');
        return t;
    };
    return q.answer.some((k) => norm(k) === norm(given[0])) ? 'correct' : 'wrong';
}

export async function collectObjectiveReview(domainId: string, tdoc: any, uid: number, onlyPid?: number) {
    const pids: number[] = (tdoc.pids || []).filter((x: any) => typeof x === 'number')
        .filter((pid: number) => onlyPid === undefined || pid === onlyPid);
    // `data` is projected so the RAW config.yaml can be read back: the
    // normalized config getList returns keeps `type` but drops `answers`.
    const pdict = await problem.getList(domainId, pids, true, false, ['docId', 'pid', 'title', 'tag', 'config', 'content', 'data'] as any, true);
    const tsdoc: any = await contest.getStatus(domainId, tdoc.docId, uid);
    const detail = tsdoc?.detail || {};
    const tasks: any[] = [];
    const rids: ObjectId[] = [];
    for (const pid of pids) {
        const pd: any = pdict[pid];
        if (!pd) continue;
        const normalized = parseConfig(pd.config);
        const objective = /^o/i.test(String(pd.pid || '')) || normalized?.type === 'objective';
        if (!objective) continue;
        // The answer key and the matching flags live in the raw config.yaml.
        const cfg = await readRawProblemConfig({ domainId, docId: pid, data: pd.data });
        if (detail[pid]?.rid) rids.push(detail[pid].rid);
        const statement = aiTutor.resolveStatement(pd, 'en');
        const points = (pd.tag || []).map((t: any) => String(t)).filter((t: string) => t);
        tasks.push({
            pid,
            label: String(pd.pid || `P${pid}`),
            title: pd.title || '',
            points,
            pointPaths: await KnowledgeModel.describeTags(domainId, points).catch(() => points),
            matching: cfg?.matching || {},
            questions: objectiveQuestionsOf(statement, cfg),
            rid: detail[pid]?.rid || null,
            score: typeof detail[pid]?.score === 'number' ? detail[pid].score : null,
        });
    }
    const rdocs = rids.length ? await record.getMulti(domainId, { _id: { $in: rids } }).project({ code: 1 }).limit(rids.length + 1).toArray() as any[] : [];
    const sheetOf = new Map(rdocs.map((r) => [String(r._id), parseAnswerSheet(r.code)]));
    const counts = {
        questions: 0, wrong: 0, unanswered: 0, correct: 0, ungraded: 0,
    };
    const grade = (t: any, q: any): ReviewQuestion => {
        const sheet = t.rid ? (sheetOf.get(String(t.rid)) || {}) : {};
        const given = sheet[q.key] || [];
        const outcome = outcomeOf(q, given, t.matching);
        counts.questions += 1;
        if (outcome === 'correct') counts.correct += 1;
        else if (outcome === 'unanswered') counts.unanswered += 1;
        else if (outcome === 'ungraded') counts.ungraded += 1;
        else counts.wrong += 1;
        return {
            key: q.key, kind: q.kind, prompt: q.prompt, options: q.options, answer: q.answer, given, outcome,
        };
    };
    for (const t of tasks) t.questions = t.questions.map((q: any) => grade(t, q));
    return { tasks, snapshot: counts };
}

/**
 * The context the model reads, in TWO parts (ai-speedup WP3): the task with
 * its questions, options and answer keys — identical for every student, so
 * it sits in the provider-cached prefix — and the student's own answers
 * marked against the key.
 */
export function objectiveReviewContext(tdoc: any, review: Awaited<ReturnType<typeof collectObjectiveReview>>): { task: string, answers: string } {
    const T: string[] = [];
    const A: string[] = [];
    for (const t of review.tasks) {
        T.push(`=== TASK "${t.title}" (${t.label}) of the homework "${tdoc.title}" — knowledge points: ${t.pointPaths.length ? t.pointPaths.join('; ') : '(unlabeled)'} ===`);
        A.push(`=== The student's answers on task ${t.label}${typeof t.score === 'number' ? ` (the student scored ${t.score}/100 on it)` : ''} ===`);
        for (const q of t.questions as ReviewQuestion[]) {
            const optText = (letters: string[]) => letters.map((l) => {
                const o = q.options.find((x) => x.letter === l);
                return o ? `${l} (${o.text})` : l;
            }).join(', ');
            T.push('', `Q${q.key} [${q.kind}]: ${q.prompt || '(see the statement)'}`);
            if (q.options.length) T.push(`  options: ${q.options.map((o) => `${o.letter}) ${o.text}`).join(' | ')}`);
            T.push(`  correct answer: ${q.answer.length ? optText(q.answer) : '(none set)'}`);
            A.push(`Q${q.key}: student's answer: ${q.given.length ? optText(q.given) : '(unanswered)'} → ${q.outcome.toUpperCase()}`);
        }
    }
    A.push('', '=== End. Write the explanation now, in English. ===');
    return { task: T.join('\n'), answers: A.join('\n') };
}

/**
 * Generate one explanation. Two callers, two treatments:
 *  • the Quick Review PRE-WARM: background lane, priority 3 (idle capacity
 *    only), no stream — nobody is looking yet;
 *  • a STUDENT'S OWN CLICK (`interactive: true`): the student is waiting,
 *    so the call takes the interactive lane (class 1, behind the tutor)
 *    and the explanation STREAMS into the page — the job carries the
 *    stream id the page attaches to (ai-speedup WP2).
 * Either way the call runs under the scheduler's `explain` cap; when the
 * scheduler has no capacity the job stays `running` with `stage:
 * 'waiting'` (the row shows "waiting for capacity · N ahead · ~T s") and
 * resubmits itself.
 */
export async function runObjectiveFeedbackJob(
    domainId: string, tdoc: any, uid: number, pid: number, opts: { priority?: 0 | 1 | 2 | 3, interactive?: boolean } = {},
): Promise<void> {
    const tid = tdoc.docId.toHexString();
    const startedAt = new Date();
    const stream = opts.interactive && aiTutor.streamingEnabled()
        ? aiTutor.aiStreams.create(uid, { feature: 'explain', lane: 'interactive', abortWhenAbandoned: false })
        : null;
    const handle = stream ? aiTutor.aiStreams.handle(stream.id) : null;
    try {
        await setObjectiveFeedbackJob(domainId, tid, uid, pid, {
            status: 'running', stage: 'running', startedAt, ...(stream ? { streamId: stream.id } : {}),
        });
        const review = await collectObjectiveReview(domainId, tdoc, uid, pid);
        if (!review.snapshot.questions) throw new Error('This task has no objective question to explain.');
        const ctx = objectiveReviewContext(tdoc, review);
        const task = review.tasks[0] || {};
        const raw = await aiTutor.aiScheduler.runWhenCapacity({
            feature: 'explain',
            lane: opts.interactive ? 'interactive' : 'background',
            priority: opts.priority ?? (opts.interactive ? 1 : 2),
            uid,
            label: 'objective feedback',
            ...(handle ? { stream: true, onQueue: (q) => handle.queue(q) } : {}),
        }, () => {
            if (stream) aiTutor.aiStreams.started(stream.id);
            return aiTutor.runObjectiveFeedback({
                task: {
                    domainId, pid, title: String(task.title || task.label || pid), label: task.label, block: ctx.task,
                },
                answers: ctx.answers,
            }, { onDelta: handle?.delta, uid, priority: opts.priority ?? (opts.interactive ? 1 : 2) });
        }, {
            onWait: (e) => {
                if (handle) handle.queue({ position: e.position, eta: e.eta });
                setObjectiveFeedbackJob(domainId, tid, uid, pid, {
                    status: 'running', stage: 'waiting', waiting: { ahead: e.position, eta: e.eta }, startedAt, ...(stream ? { streamId: stream.id } : {}),
                }).catch(() => { /* cosmetic */ });
            },
        });
        const generatedAt = await setObjectiveFeedbackReport(domainId, tid, uid, pid, raw.trim(), review.snapshot);
        await setObjectiveFeedbackJob(domainId, tid, uid, pid, { status: 'done', startedAt, finishedAt: new Date() });
        if (stream) aiTutor.aiStreams.finish(stream.id, { report: raw.trim(), generatedAt });
        logger.info('[objective-feedback] %s/%s uid=%d pid=%d: %d question(s) explained', domainId, tid, uid, pid, review.snapshot.questions);
    } catch (e) {
        logger.warn('[objective-feedback] %s/%s uid=%d pid=%d failed: %s', domainId, tid, uid, pid, e.message);
        if (stream) aiTutor.aiStreams.fail(stream.id, e);
        await setObjectiveFeedbackJob(domainId, tid, uid, pid, {
            status: 'failed', startedAt, finishedAt: new Date(), error: String(e.message || e).slice(0, 300),
        }).catch(() => {});
    }
}

/** One task's explanation state (the row button and the modal read this). */
export async function objectiveFeedbackState(domainId: string, tdoc: any, uid: number, pid: number, withCounts = true) {
    const tid = tdoc.docId.toHexString();
    const doc = await getObjectiveFeedback(domainId, tid, uid, pid);
    let job = doc?.job || null;
    if (objectiveFeedbackJobStale(job, JOB_SILENCE_MS)) job = { ...job!, status: 'failed', error: 'The explanation stopped (the server may have restarted). Try again.' };
    // A stream id is only useful while this process still holds the stream.
    if (job?.streamId && !aiTutor.aiStreams.get(job.streamId)) job = { ...job, streamId: undefined };
    const counts = withCounts ? (await collectObjectiveReview(domainId, tdoc, uid, pid)).snapshot : null;
    return {
        pid, report: doc?.report || null, generatedAt: doc?.generatedAt || null, snapshot: doc?.snapshot || null, counts, job,
    };
}

export class HomeworkObjectiveFeedbackHandler extends Handler {
    tdoc: any;

    @param('tid', Types.ObjectId)
    async prepare(domainId: string, tid: ObjectId) {
        this.tdoc = await contest.get(domainId, tid);
        if (!this.tdoc) throw new NotFoundError(tid);
        // Homework, or a TEST once its Quick Review policy shows students
        // their feedback (lib/quick_review.ts studentFeedbackVisible: the
        // container has ended for everyone and, under `on_teacher`, the
        // teacher has released it). Any other rule: not found.
        if (this.tdoc.rule !== 'homework') {
            if (!studentFeedbackVisible(this.tdoc, await getQuick(domainId, String(tid)))) throw new NotFoundError(tid);
        }
        // Only once the homework has ended (the late window included).
        if (!contest.isDone(this.tdoc)) throw new HomeworkNotLiveError(tid);
        const tsdoc = await contest.getStatus(domainId, tid, this.user._id);
        if (!tsdoc?.attend) throw new ForbiddenError('Only students who took part in this activity can ask for an explanation.');
    }

    @param('tid', Types.ObjectId)
    @param('pid', Types.Int)
    @param('job', Types.Boolean, true)
    async get(domainId: string, tid: ObjectId, pid: number, jobOnly = false) {
        if (!(this.tdoc.pids || []).includes(pid)) throw new NotFoundError(pid);
        this.response.body = await objectiveFeedbackState(domainId, this.tdoc, this.user._id, pid, !jobOnly);
    }

    @param('tid', Types.ObjectId)
    @param('pid', Types.Int)
    async post(domainId: string, tid: ObjectId, pid: number) {
        if (!(this.tdoc.pids || []).includes(pid)) throw new NotFoundError(pid);
        if (!aiTutor.tutorConfigured()) throw new ForbiddenError('The AI tutor is not configured. Please ask the administrator to set an API key.');
        const doc = await getObjectiveFeedback(domainId, tid.toHexString(), this.user._id, pid);
        if (doc?.job?.status === 'running' && !objectiveFeedbackJobStale(doc.job, JOB_SILENCE_MS)) {
            this.response.body = { started: false, job: doc.job };
            return;
        }
        await this.limitRate('ai_objective_feedback', 600, 10, '{{user}}');
        const job = { status: 'running' as const, startedAt: new Date() };
        await setObjectiveFeedbackJob(domainId, tid.toHexString(), this.user._id, pid, job);
        // Detached on purpose; a student's own click streams (interactive lane).
        runObjectiveFeedbackJob(domainId, this.tdoc, this.user._id, pid, { interactive: true });
        // The job block is written synchronously at the start of the runner
        // (with the stream id), so the page can attach right away.
        const fresh = await getObjectiveFeedback(domainId, tid.toHexString(), this.user._id, pid);
        this.response.body = { started: true, job: fresh?.job || job };
    }
}

/**
 * What the PAPER page (handler/self_learning.ts ObjectivePaperHandler)
 * needs to put an "Explain" button next to every objective question the
 * student did not get right: their outcome per task (from the counted
 * record's status and score — the same numbers the results table shows)
 * and which tasks already have a stored explanation.
 */
export async function paperFeedbackFor(h: any, domainId: string, tdoc: any, detail: Record<number, any>) {
    const tid = tdoc.docId.toHexString();
    const docs = await listObjectiveFeedback(domainId, tid, h.user._id);
    const byPid: Record<string, any> = {};
    for (const d of docs) {
        byPid[String(d.pid)] = {
            hasReport: !!d.generatedAt,
            running: d.job?.status === 'running' && !objectiveFeedbackJobStale(d.job, JOB_SILENCE_MS),
        };
    }
    const taskOutcome = (docId: number): 'correct' | 'partial' | 'wrong' | 'unanswered' => {
        const d = detail?.[docId];
        if (!d?.rid) return 'unanswered';
        if (d.status === STATUS.STATUS_ACCEPTED || (d.score || 0) >= 100) return 'correct';
        return (d.score || 0) > 0 ? 'partial' : 'wrong';
    };
    const route = tdoc.rule === 'homework' ? 'homework_objective_feedback' : 'contest_objective_feedback';
    return { url: h.url(route, { tid: tdoc.docId }), byPid, outcomeOf: taskOutcome };
}

/**
 * The ONLY registration of this route. handler/objective_feedback.ts (an
 * older, homework-wide copy of the feature) used to register the same name
 * and path too, and won every time — a router serves the first matching
 * layer, and this call only happens after homework.ts has awaited the
 * scoreboard service — so the page polled a handler that ignored `pid`
 * and never found its job or report ("The explanation could not be
 * generated."). That file is now an empty stub; keep it that way.
 */
export function applyObjectiveFeedback(ctx) {
    ctx.Route('homework_objective_feedback', '/homework/:tid/objective-feedback', HomeworkObjectiveFeedbackHandler, PERM.PERM_VIEW_HOMEWORK);
    // ⚡ The same handler for TESTS (Quick Review): the paper passes this
    // URL once the students' feedback is visible (see prepare()).
    ctx.Route('contest_objective_feedback', '/contest/:tid/objective-feedback', HomeworkObjectiveFeedbackHandler, PERM.PERM_VIEW_CONTEST);
    // Sweep the documents the retired handler left behind (see the model).
    purgeMalformedObjectiveFeedback()
        .then((n) => { if (n) logger.info('[objective-feedback] removed %d malformed document(s) left by the retired handler', n); })
        .catch((e) => logger.warn('[objective-feedback] cleanup skipped: %s', e.message));
}
