export type CompilableSource = string | {
    file: string;
    lang: string;
};

export enum ProblemType {
    Default = 'default',
    SubmitAnswer = 'submit_answer',
    Interactive = 'interactive',
    Communication = 'communication',
    Objective = 'objective',
    Remote = 'remote_judge',
}

export interface TestCaseConfig {
    input: string;
    output: string;
    time?: string;
    memory?: string;
    score?: number;
}

export enum SubtaskType {
    min = 'min',
    max = 'max',
    sum = 'sum',
}

export interface SubtaskConfig {
    time?: string;
    memory?: string;
    score?: number;
    if?: number[];
    id?: number;
    type?: SubtaskType;
    cases?: TestCaseConfig[];
}

export type DetailType = 'full' | 'case' | 'none';

export interface ProblemConfigFile {
    type?: ProblemType;
    subType?: string;
    target?: string;
    score?: number;
    time?: string;
    memory?: string;
    filename?: string;
    checker_type?: string;
    num_processes?: number;
    user_extra_files?: string[];
    judge_extra_files?: string[];
    detail?: DetailType | boolean;
    answers?: Record<string, [string | string[], number]>;
    redirect?: string;
    cases?: TestCaseConfig[];
    subtasks?: SubtaskConfig[];
    langs?: string[];
    multi_pass?: number;
    checker?: CompilableSource;
    interactor?: CompilableSource;
    manager?: CompilableSource;
    validator?: CompilableSource;
    time_limit_rate?: Record<string, number>;
    memory_limit_rate?: Record<string, number>;
    /**
     * PTA fork — FUNCTION TASKS. Per language family (`c`, `cc`, `py`, …):
     * the judge program the student's fragment is spliced into. A comment
     * line reading "Your function will be put here" (PTA's convention) marks
     * the splice point; with no marker the fragment is appended, which is
     * what PTA's own sample program does.
     * The judge never sees this key — the server wraps before dispatch
     * (hydrooj model/record.ts wrapFunctionCode).
     */
    template?: Record<string, string>;
    /** The empty function the scratchpad opens with, per language family. */
    stub?: Record<string, string>;
    /**
     * PTA fork — SUBJECTIVE TASKS (pid S…). What the student hands in:
     * `report` = ONE PDF report, graded against `rubric` by the AI grader
     * (lib/subjective_grader.ts) once the homework ends; `project` = a
     * project packed in a zip (submitted like before; automatic grading of
     * projects is not implemented yet). Absent = legacy free-form task.
     */
    subjective?: SubjectiveTaskConfig;
    /** The grading rubric of a subjective task (lib/subjective_rubric.ts validates it). */
    rubric?: SubjectiveRubric;
}

/* ------------------------------------------------------------------ */
/*  PTA fork — subjective tasks: submission type and rubric            */
/* ------------------------------------------------------------------ */
export type SubjectiveTaskType = 'report' | 'project';

export interface SubjectiveTaskConfig {
    type: SubjectiveTaskType;
}

/** One achievement level of a criterion (e.g. "Excellent" = 9-10 points). */
export interface RubricLevel {
    /** The points this level is worth (≤ the criterion's maxPoints). */
    points: number;
    /** Short label: "Excellent", "Adequate", "Missing"… */
    label: string;
    /** What a submission at this level looks like — the grader's yardstick. */
    descriptor?: string;
}

export interface RubricCriterion {
    /** Stable id, generated by the builder (`c1`, `c2`…); grades and comments refer to it. */
    id: string;
    title: string;
    /** What is being assessed and what evidence to look for. */
    description?: string;
    maxPoints: number;
    /** Optional achievement levels, highest first; without them the criterion is scored continuously. */
    levels?: RubricLevel[];
}

export interface SubjectiveRubric {
    version: 1;
    /** Sum of the criteria's maxPoints (validated); the task's score = points / total × 100. */
    total: number;
    criteria: RubricCriterion[];
    /** Free text for the grader: course context, what to be strict or lenient about. */
    graderNotes?: string;
    /** Pages beyond this are not read by the grader (0 = no limit). */
    maxPages?: number;
}

export interface FileInfo {
    /** storage path */
    _id: string;
    /** filename */
    name: string;
    /** file size (in bytes) */
    size: number;
    etag: string;
    lastModified: Date;
}

export interface JudgeMeta {
    problemOwner: number;
    hackRejudge?: string;
    rejudge?: boolean | 'controlled';
    // FIXME stricter types
    type?: string;
}

export interface RecordJudgeInfo {
    score: number;
    memory: number;
    time: number;
    judgeTexts: (string | JudgeMessage)[];
    compilerTexts: string[];
    testCases: Required<TestCase>[];
    /** judge uid */
    judger: number;
    judgeAt: Date;
    status: number;
    subtasks?: Record<number, SubtaskResult>;
}

export interface RecordPayload extends RecordJudgeInfo {
    domainId: string;
    pid: number;
    uid: number;
    lang: string;
    code: string;
    rejudged: boolean;
    source?: string;
    progress?: number;
    /** pretest */
    input?: string | string[];
    /** hack target rid */
    hackTarget?: string;
    /** 0 if pretest&script */
    contest?: string;

    files?: Record<string, string>;
}

export interface JudgeRequest extends Omit<RecordPayload, 'testCases'> {
    priority: number;
    type: 'judge' | 'generate';
    rid: string;
    config: ProblemConfigFile;
    meta: JudgeMeta;
    data: FileInfo[];
    source: string;
    trusted: boolean;
}

export interface TestCase {
    id?: number;
    subtaskId?: number;
    score?: number;
    time: number;
    memory: number;
    status: number;
    message: string | JudgeMessage;
}

export interface JudgeMessage {
    message: string;
    params?: string[];
    stack?: string;
}

export interface SubtaskResult {
    type: SubtaskType;
    score: number;
    status: number;
}

export interface JudgeResultBody {
    key: string;
    domainId: string;
    rid: string;
    judger?: number;
    progress?: number;
    addProgress?: number;
    case?: TestCase;
    cases?: TestCase[];
    status?: number;
    score?: number;
    /** in miliseconds */
    time?: number;
    /** in kilobytes */
    memory?: number;
    message?: string | JudgeMessage;
    compilerText?: string;
    nop?: boolean;
    subtasks?: Record<number, SubtaskResult>;
}
