import { ObjectId } from 'mongodb';
import { load as yamlLoad } from 'js-yaml';
import { ForbiddenError, HomeworkNotLiveError, NotFoundError } from '../error';
import * as aiTutor from '../lib/ai_tutor';
import { objectiveQuestionsOf, parseAnswerSheet, sameSet } from '../lib/activity_report';
import { Logger } from '../logger';
import { PERM } from '../model/builtin';
import * as contest from '../model/contest';
import KnowledgeModel from '../model/knowledge';
import {
    getObjectiveFeedback, objectiveFeedbackJobStale, setObjectiveFeedbackJob, setObjectiveFeedbackReport,
} from '../model/objective_feedback';
import problem from '../model/problem';
import record from '../model/record';
import { Handler, param, Types } from '../service/server';

const logger = new Logger('objective-feedback');

/**
 * PTA fork — AI REVIEW OF A STUDENT'S OBJECTIVE ANSWERS.
 *
 * Once a homework has ENDED (past the late window, i.e. contest.isDone —
 * endAt is the hard deadline), a student who took part can ask, from the
 * homework page, for a personal review of the objective tasks: for every
 * question they got wrong, partially right or left blank — the correct
 * answer, why it is right, what their own choice suggests they
 * misunderstood, a tip — and what to review next. Programming tasks are
 * not covered here; they have the per-submission AI Suggestions.
 *
 * What the model reads (collectObjectiveReview): each objective task's
 * knowledge points; each question's text, options and ANSWER KEY (from
 * config.yaml, as the judge reads it); the student's answers from the
 * submission that COUNTS for the homework (tsdoc.detail[pid].rid — the
 * scoreboard's), marked with the judge's own rules (multi-select: full /
 * partial / wrong; blanks honour the task's ignoreCase / ignoreSpaces).
 *
 * The review is generated by a BACKGROUND JOB the page polls (the report
 * is stored; closing the page does not interrupt it) and kept until the
 * student regenerates it.
 */

const JOB_SILENCE_MS = 5 * 60 * 1000;

interface ReviewQuestion {
    key: string;
    kind: string;
    prompt: string;
    options: { letter: string, text: string }[];
    answer: string[];
    given: string[];
    outcome: 'correct' | 'partial' | 'wrong' | 'unanswered' | 'ungraded';
}

function parseConfig(cfg: any): any {
    if (typeof cfg !== 'string') return cfg && typeof cfg === 'object' ? cfg : null;
    try {
        return yamlLoad(cfg);
    } catch (e) {
        return null;
    }
}

/** The judge's comparison for one question (hydrojudge/src/judge/objective.ts). */
function outcomeOf(q: { kind: string, answer: string[] }, given: string[], matching: any): ReviewQuestion['outcome'] {
    if (!given.length) return 'unanswered';
    if (!q.answer.length) return 'ungraded';
    if (q.kind === 'multiselect') {
        const key = new Set(q.answer);
        const ans = new Set(given);
        if (ans.size === key.size && [...ans].every((x) => key.has(x))) return 'correct';
        if ([...ans].every((x) => key.has(x))) return 'partial';
        return 'wrong';
    }
    if (q.kind === 'select') return sameSet(given, q.answer) ? 'correct' : 'wrong';
    const norm = (s: string) => {
        let t = String(s ?? '').trim();
        if (matching?.ignoreCase) t = t.toLowerCase();
        if (matching?.ignoreSpaces) t = t.replace(/\s+/g, '');
        return t;
    };
    return q.answer.some((k) => norm(k) === norm(given[0])) ? 'correct' : 'wrong';
}

export async function collectObjectiveReview(domainId: string, tdoc: any, uid: number) {
    const pids: number[] = (tdoc.pids || []).filter((x: any) => typeof x === 'number');
    const pdict = await problem.getList(domainId, pids, true, false, ['docId', 'pid', 'title', 'tag', 'config', 'content'] as any, true);
    const tsdoc: any = await contest.getStatus(domainId, tdoc.docId, uid);
    const detail = tsdoc?.detail || {};
    const tasks: any[] = [];
    const rids: ObjectId[] = [];
    for (const pid of pids) {
        const pd: any = pdict[pid];
        if (!pd) continue;
        const cfg = parseConfig(pd.config);
        const objective = /^o/i.test(String(pd.pid || '')) || cfg?.type === 'objective';
        if (!objective) continue;
        if (detail[pid]?.rid) rids.push(detail[pid].rid);
        const statement = aiTutor.resolveStatement(pd, 'en');
        const points = (pd.tag || []).map((t: any) => String(t)).filter((t: string) => t);
        tasks.push({
            pid,
            label: String(pd.pid || `P${pid}`),
            title: pd.title || '',
            points,
            pointPaths: await KnowledgeModel.describeTags(domainId, points).catch(() => points),
            matching: cfg?.matching || {},
            questions: objectiveQuestionsOf(statement, cfg),
            rid: detail[pid]?.rid || null,
            score: typeof detail[pid]?.score === 'number' ? detail[pid].score : null,
        });
    }
    const rdocs = rids.length ? await record.getMulti(domainId, { _id: { $in: rids } }).project({ code: 1 }).limit(rids.length + 1).toArray() as any[] : [];
    const sheetOf = new Map(rdocs.map((r) => [String(r._id), parseAnswerSheet(r.code)]));
    const counts = { questions: 0, wrong: 0, unanswered: 0, correct: 0 };
    const grade = (t: any, q: any): ReviewQuestion => {
        const sheet = t.rid ? (sheetOf.get(String(t.rid)) || {}) : {};
        const given = sheet[q.key] || [];
        const outcome = outcomeOf(q, given, t.matching);
        counts.questions += 1;
        if (outcome === 'correct') counts.correct += 1;
        else if (outcome === 'unanswered') counts.unanswered += 1;
        else if (outcome !== 'ungraded') counts.wrong += 1;
        return {
            key: q.key, kind: q.kind, prompt: q.prompt, options: q.options, answer: q.answer, given, outcome,
        };
    };
    for (const t of tasks) t.questions = t.questions.map((q: any) => grade(t, q));
    return { tasks, snapshot: counts };
}

/** The context block the model reads: every objective question with key and the student's answer. */
export function objectiveReviewContext(tdoc: any, review: Awaited<ReturnType<typeof collectObjectiveReview>>): string {
    const L: string[] = [`=== HOMEWORK "${tdoc.title}" — objective questions: ${review.snapshot.questions} (correct ${review.snapshot.correct}, wrong ${review.snapshot.wrong}, unanswered ${review.snapshot.unanswered}) ===`];
    for (const t of review.tasks) {
        L.push('', `--- ${t.label} "${t.title}" — knowledge points: ${t.pointPaths.length ? t.pointPaths.join('; ') : '(unlabeled)'}${typeof t.score === 'number' ? ` — the student's score on this task: ${t.score}/100` : ''} ---`);
        for (const q of t.questions as ReviewQuestion[]) {
            const opts = q.options.length ? `\n  options: ${q.options.map((o) => `${o.letter}) ${o.text}`).join(' | ')}` : '';
            const optText = (letters: string[]) => letters.map((l) => {
                const o = q.options.find((x) => x.letter === l);
                return o ? `${l} (${o.text})` : l;
            }).join(', ');
            L.push(`Q${q.key} [${q.kind}]: ${q.prompt || '(see statement)'}${opts}`);
            L.push(`  correct answer: ${q.answer.length ? optText(q.answer) : '(none set)'}`);
            L.push(`  student's answer: ${q.given.length ? optText(q.given) : '(unanswered)'} → ${q.outcome.toUpperCase()}`);
        }
    }
    L.push('', '=== End. Write the review now. ===');
    return L.join('\n');
}

export async function runObjectiveFeedbackJob(domainId: string, tdoc: any, uid: number): Promise<void> {
    const tid = tdoc.docId.toHexString();
    const startedAt = new Date();
    try {
        await setObjectiveFeedbackJob(domainId, tid, uid, { status: 'running', startedAt });
        const review = await collectObjectiveReview(domainId, tdoc, uid);
        if (!review.snapshot.questions) throw new Error('This homework has no objective questions to review.');
        const raw = await aiTutor.callWithRetry(() => aiTutor.runObjectiveFeedback(objectiveReviewContext(tdoc, review)), { label: 'objective feedback' });
        await setObjectiveFeedbackReport(domainId, tid, uid, raw.trim(), review.snapshot);
        await setObjectiveFeedbackJob(domainId, tid, uid, { status: 'done', startedAt, finishedAt: new Date() });
        logger.info('[objective-feedback] %s/%s uid=%d: %d question(s) reviewed', domainId, tid, uid, review.snapshot.questions);
    } catch (e) {
        logger.warn('[objective-feedback] %s/%s uid=%d failed: %s', domainId, tid, uid, e.message);
        await setObjectiveFeedbackJob(domainId, tid, uid, {
            status: 'failed', startedAt, finishedAt: new Date(), error: String(e.message || e).slice(0, 300),
        }).catch(() => {});
    }
}

/** The page card's state for one student (also used by the HomeworkDetail hook). */
export async function objectiveFeedbackState(domainId: string, tdoc: any, uid: number, withCounts = true) {
    const tid = tdoc.docId.toHexString();
    const doc = await getObjectiveFeedback(domainId, tid, uid);
    let job = doc?.job || null;
    if (objectiveFeedbackJobStale(job, JOB_SILENCE_MS)) job = { ...job!, status: 'failed', error: 'The review stopped (the server may have restarted). Generate it again.' };
    const counts = withCounts ? (await collectObjectiveReview(domainId, tdoc, uid)).snapshot : null;
    return {
        report: doc?.report || null,
        generatedAt: doc?.generatedAt || null,
        snapshot: doc?.snapshot || null,
        counts,
        job,
    };
}

class HomeworkObjectiveFeedbackHandler extends Handler {
    tdoc: any;

    @param('tid', Types.ObjectId)
    async prepare(domainId: string, tid: ObjectId) {
        this.tdoc = await contest.get(domainId, tid);
        if (this.tdoc.rule !== 'homework') throw new NotFoundError(tid);
        // Only once the homework has ended (the late window included).
        if (!contest.isDone(this.tdoc)) throw new HomeworkNotLiveError(tid);
        const tsdoc = await contest.getStatus(domainId, tid, this.user._id);
        if (!tsdoc?.attend) throw new ForbiddenError('Only students who took part in this homework can ask for a review.');
    }

    @param('tid', Types.ObjectId)
    @param('job', Types.Boolean, true)
    async get(domainId: string, tid: ObjectId, jobOnly = false) {
        this.response.body = await objectiveFeedbackState(domainId, this.tdoc, this.user._id, !jobOnly);
    }

    @param('tid', Types.ObjectId)
    async post(domainId: string, tid: ObjectId) {
        if (!aiTutor.tutorConfigured()) throw new ForbiddenError('The AI tutor is not configured. Please ask the administrator to set an API key.');
        const doc = await getObjectiveFeedback(domainId, tid.toHexString(), this.user._id);
        if (doc?.job?.status === 'running' && !objectiveFeedbackJobStale(doc.job, JOB_SILENCE_MS)) {
            this.response.body = { started: false, job: doc.job };
            return;
        }
        await this.limitRate('ai_objective_feedback', 600, 3, '{{user}}');
        const job = { status: 'running' as const, startedAt: new Date() };
        await setObjectiveFeedbackJob(domainId, tid.toHexString(), this.user._id, job);
        runObjectiveFeedbackJob(domainId, this.tdoc, this.user._id); // detached on purpose
        this.response.body = { started: true, job };
    }
}

export async function apply(ctx) {
    ctx.Route('homework_objective_feedback', '/homework/:tid/objective-feedback', HomeworkObjectiveFeedbackHandler, PERM.PERM_VIEW_HOMEWORK);
    /*
     * The homework page's card (homework_detail.html): for a student who
     * took part, once the homework has ended — the counts, the stored
     * review and the job state, so the page can render immediately.
     */
    ctx.on('handler/after/HomeworkDetail#get' as any, async (h: any) => {
        try {
            if (!h?.response?.template || !h.tdoc) return;
            const tdoc = h.tdoc;
            if (tdoc.rule !== 'homework') return;
            // Students who took part only (staff have no answers to review).
            const tsdoc = h.response.body?.tsdoc;
            if (!tsdoc?.attend || h.user.own(tdoc) || h.user.hasPerm(PERM.PERM_EDIT_HOMEWORK)) return;
            const pids: number[] = tdoc.pids || [];
            const pdict = h.response.body.pdict || {};
            const hasObjective = pids.some((pid) => /^o/i.test(String(pdict[pid]?.pid || '')));
            const url = h.url('homework_objective_feedback', { tid: tdoc.docId });
            // Before the hard deadline the card announces when the review opens.
            if (!contest.isDone(tdoc)) {
                if (!hasObjective) return;
                h.response.body.objectiveFeedback = { pending: true, availableAt: tdoc.endAt, url };
                return;
            }
            const state = await objectiveFeedbackState(h.args.domainId, tdoc, h.user._id, true);
            if (!hasObjective && !state.counts?.questions) return;
            h.response.body.objectiveFeedback = { ...state, url };
            h.UiContext.objectiveFeedback = { url, job: state.job };
        } catch (e) {
            logger.warn('[objective-feedback] homework page card failed: %s', e.message);
        }
    });
}
